### ISSUE TITLE
Fix ma p＊＊＊s

### ISSUE THREAD

**Issue by SuiOni** [marielouiese/AnalyseUebung#1]
Fix ma p＊＊＊sFix ma p＊＊＊sFix ma p＊＊＊s

**Comment by marielouiese** [comment]
Was genau ist das issue Sak? :D

**Comment by SuiOni** [comment]
Fix machen Penis haha


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Marie-Louise Timcke <notifications@github.com> Date: 4/22/16  16:24  (GMT+01:00) To: marielouiese/AnalyseUebung <AnalyseUebung@noreply.github.com> Cc: Sak Zirai <s.zirai@live.de>, Author <author@noreply.github.com> Subject: Re: [marielouiese/AnalyseUebung] Fix ma p＊＊＊s (#1) 
Was genau ist das issue Sak? :D
